name: Auto Label

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Apply labels based on changed paths
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner; const repo = context.repo.repo;
            const files = await github.paginate(github.rest.pulls.listFiles, {owner, repo, pull_number: pr.number});
            const labels = new Set();
            
            // Check for component areas
            if (files.some(f=>f.filename.startsWith('tasks/'))) labels.add('lgda-task');
            if (files.some(f=>f.filename.includes('bq.py')||f.filename.includes('bigquery'))) labels.add('bigquery');
            if (files.some(f=>f.filename.includes('llm.py')||f.filename.includes('gemini')||f.filename.includes('bedrock'))) labels.add('llm');
            if (files.some(f=>f.filename.includes('config.py')||f.filename.includes('configuration'))) labels.add('infrastructure');
            if (files.some(f=>f.filename.includes('agent/')||f.filename.includes('langgraph'))) labels.add('langgraph');
            if (files.some(f=>f.filename.startsWith('tests/'))) labels.add('testing');
            if (files.some(f=>f.filename.startsWith('docs/adr/'))) labels.add('architecture');
            if (files.some(f=>f.filename.startsWith('.github/'))) labels.add('ci-cd');
            
            // Check for task IDs in PR title/body
            const text = (pr.title || '') + '\n' + (pr.body || '');
            const taskIds = text.match(/LGDA-\d{3}/g) || [];
            if (taskIds.length > 0) {
              labels.add('has-task-id');
              // Add specific task number labels if needed
              for (const taskId of taskIds) {
                labels.add(`task:${taskId.toLowerCase()}`);
              }
            }
            
            // Security-related changes
            if (files.some(f=>f.filename.includes('sql') && f.filename.includes('validation'))) labels.add('security');
            if (files.some(f=>f.filename.includes('credential')||f.filename.includes('auth'))) labels.add('security');
            
            if (labels.size) {
              await github.rest.issues.addLabels({owner, repo, issue_number: pr.number, labels: Array.from(labels)});
            }
